### ISSUE TITLE
Why the e2_tts module loss and  DurationPredictor loss are added to a single loss?

### ISSUE THREAD

**Issue by JohnHerry** [bfs18/e2_tts#15]
hi, I need some help about the loss in the project, the reconstruction loss and the duration prediction loss are added as one single loss for optimize, instead of optimize them independently.  since e2_tts and duration_predictor are two different network, why we can make such a design here?

**Comment by bfs18** [comment]
Hi @JohnHerry , Actually, I didn't strictly follow the E2E-TTS paper here. In the current implementation, the duration predictor and acoustic model share the same text encoder, so I optimize their losses together.

**Comment by JohnHerry** [comment]
Thank you for the help.    
My configuration is     
```
backbone:
    class_path: rfwave.dit.DiTRFE2ETTSMutiTaskBackbone
    init_args:
        input_channels: 512
        output_channels: 80
        dim: 1024
        intermediate_dim: 2048
        num_layers: 20
        num_heads: 16

input_adaptor:
    class_path: rfwave.input.E2ECtxCharInputAdaptor
    init_args:
        embedding_dim: 512
        vocab_size: 338
        ctx_dim: 80
        num_layers: 4
```       
My corpus is Chinese/English mixed, about 80K hours totally , ,and the totally phoneme set contains 337 items.  model trained on 6 cards with batch size=10 samples, each sample is about 3 to 20 seconds.   I have trained to about 400K steps, nearly one epoch (every epoch contains more then 500K steps), but the validation output is not good.  
The grad_norm is 0.8 now,   The traning loss is nearly 0.05,  about 0.02 for dur_loss and 0.02 for rf_loss;   but the validation loss is over 0.5.   both training and validation losses refuse to go down significantly.

![A](https://github.com/user-attachments/assets/bcfc82bc-c440-4123-a8dd-83d50708bfaa)
![B](https://github.com/user-attachments/assets/5170d957-aa63-437e-a461-6f6826b5211f)
![D](https://github.com/user-attachments/assets/558ce0c8-5aee-4dd6-9b65-56c6f4123845)


With the vocos vocoder, the generated mel sounds like a puff of nonsense concatenate a puff of noise, no clear speech generated. is there any traning config I can adjust here?
