### ISSUE TITLE
训练LibriTTS_R的效果

### ISSUE THREAD

**Issue by ABC0408** [bfs18/e2_tts#6]
我用libritts训练了模型，看loss像是收敛了
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/b40c68b7-8e5a-4444-959a-b4aba4d8d4e3">
下面是我用LJSpeech的数据进行推理的结果：
https://drive.google.com/drive/folders/1_mkx0ze_Y0P1uX3kCjAWu3rgHGhyUQeP?usp=sharing
我有两个疑问：
1. 和你给出来的用LJSpeech训练推理出的效果相比，我合成的*-full.wav前面的效果怎么都差挺多的。
2. 是不是因为数据量还是少的原因，克隆的效果还可以再提高。比如要几万小时的数据吗？

**Comment by bfs18** [comment]
250k step太少了，端到端TTS的训练指标对效果没有参考价值，因为合成的谱phone的边界和gt的不对齐。

**Comment by ABC0408** [comment]
> @ABC0408
> 
> 1. 250k step太少了，端到端TTS的训练指标对效果没有参考价值，因为合成的谱phone的边界和gt的不对齐。*-full前面那段是prompt，那一段算loss的时候被mask掉了，我猜测是因为模型能区分出有gt mel的区域和没有gt mel的区域，而有gt mel的区域没有算loss优化，所以效果不好。
> 2. 我认为libritts的数据量应该是够的，一般来说数据越多效果会越好，但模型规模也要随之增大，要实验确定一下。

我用的8卡，训练了大概300个epoch，效果和250k步的时候差不多，如果loss没有太大参考的话，梯度也基本上都是收敛了。
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/00067c98-7de7-4287-8a54-2e271966cdc9">
我用奥巴马的音色也合成了两条，音色是像的，就是自然度还差点。
[test_output_444k.zip](https://github.com/user-attachments/files/16737395/test_output_444k.zip)
请问，如何要是加大模型的话，建议修改哪些参数？

**Comment by bfs18** [comment]
@ABC0408 主要改backbone的参数，比如
https://github.com/bfs18/e2_tts/blob/2a3c19259aac46ff050de818a2947dd487f3772f/config/e2_tts.yaml#L52

```
    backbone:
      class_path: rfwave.dit.DiTRFE2ETTSMultiTaskBackbone
      init_args:
        input_channels: 512
        output_channels: 100
        dim: 512
        intermediate_dim: 2048
        num_layers: 24
        num_heads: 8
```
